### ISSUE TITLE
Canary vs Bug (Steem Plus Extension)

### ISSUE THREAD

**Issue by deveerei** [stoodkev/SteemPlus#1]
<center>
![bug.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510150087/nmqognym7v8eitlbt7dw.gif)
<sub>Gif by @deveerei</sub></center>

I recently installed Steem Plus on my Google Chrome Canary, which is my main browser (I was already trying it out on the regular version of Chrome), and I encountered a bug. Here's what it looks like on my laptop's screen:

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510139572/a9lxa2twguqpffeewtyq.png)</center>

Before I begin, here are some technical specs that may be needed for this:

| Element | Details |
| --------- | --------|
| Website | Steemit.com |
| Extension | Steem Plus |
| Link | [Webstore](utm_source=chrome-app-launcher-info-dialog) |
| Browser |	Google Chrome |
| Browser Version |	Version 64.0.3254.0 (Official Build) canary (64-bit) |
| Time Reported |	2 PM Wednesday, 8 November 2017 UTC+08:00 |
| Issue |	See Above Report |

***

<center>![Module_80px.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510142888/zoy415i5zc5trjpbetjy.png)</center>

It seems these set of elements are the cause of this problem:

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510139845/gaw8qezczxxr46xjsjl3.png)</center>

Here's the view from [the CSS codes](https://steemit.com/assets/app-c0c9fbff65f09c6b8712.css):

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510139875/fonnbta2tcrvhm25jvps.png)</center>

So, I tried playing with it  till it gets me a fix. The first thing I tried is turning off those elements.

<code>display: -webkit-box;
    display: -ms-flexbox;
    display: flex</code>

It only made a difference on the third element: <code>display: flex</code>. Turning it off does fix the issue with the stretched out @steem-plus logo, however doing so will get us another issue:

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510140056/pvhidntftkjdfvmvwlwz.png)</center>

A missing Steemit logo! We can't have it that way since it will not be Steemit.com without its logo up there.

And so we tried checking other places in the html and css codes, to no avail. Turning things off here and there till I see relevant changes but there are none.

The next thing I tried doing is changing some attributes for those elements. Still, I kept tinkering with the 3 elements I mentioned earlier:

<code>display: -webkit-box;
    display: -ms-flexbox;
    display: flex</code>

The same thing - it only makes a difference if I change the values for the 3rd one: <code>display: flex</code>. I tried changing it to numerous things and what worked is the <code>inherit</code> value:

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510140282/uohqc5jyjcmg4b4u1ive.png)
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510140291/wj9xhqnmrenboxaxlds7.png)</center>

Doing this fixed the issue with the stretching of the @steem-plus logo and the possible disappearing of the Steemit logo. Take a look:

<center>![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510140664/iowhmwyxcctnudw8pohn.png)</center>

The fault lies on the codes written for <code>.menu > li > a</code>:

<code>.menu > li > a {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex; }</code>

***

Instead of <code>display: flex</code>, it needs to be <code>display: inherit</code>.

Why does it work? To be honest it's a mystery for me. 

> The inherit keyword is one that specifies that a property should inherit its value from its parent element. - [w3](https://www.w3schools.com/cssref/css_inherit.asp)

> The flex property specifies the length of the item, that is relative to the rest of the flexible items inside of the same container. The flex property is a short-hand for the 'flex-grow', 'flex-shrink', and the 'flex-basis' properties. - [w3](https://www.w3schools.com/cssref/css3_pr_flex.asp)
<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@deveerei/canary-vs-bug-steem-plus-extension">Utopian.io</a></em><hr/>

**Comment by fabiyamada** [comment]
it would be better to use an image with proper without rescaling with css
