### ISSUE TITLE
Bug: Steemplus extension doesn't show any power up history on wallet instead it shows two(send and receive steem) transaction

### ISSUE THREAD

**Issue by sourovafrin** [stoodkev/SteemPlus#106]
#### Expected behavior

Steemplus extension add many features on steemit. I expected that i will be able to see my power up history on my wallet keeping steemplus extension enabled.

#### Actual behavior

Today morning i powered up some steem. But when i checked it keeping steemplus extension enabled, i found no history of power up. I only saw 2 transaction history of steem to my ownself.
As we can transfer sbd or steem to ownself i was confused if i had done it or not. Then i checked it on busy and found that actually that transaction is powered up history which is showing wrong.

#### How to reproduce
- Go [here](https://github.com/steemplus/SteemPlus) and read the read me file to download the extension for your specific browser.

- After installing the extension, click on it and login through steemconnect.

- Now go on your steemit wallet.

- Do a power up for check. if you have a power up transaction recently then just try to search it out.

- You will see no power up history, instead you will see 2 transaction(send and receive) of that amount of steem power which you powered up.

N:B: As there will be no power up history you can find it, take help of busy to find out the time of power up and search by that time. But if you power up while replicating the bug, you will find the transaction on top and it will be easy to check.

* Browser version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)

* Operating system: Windows 8.1

#### Recording Of The Bug

https://ipfs.busy.org/ipfs/QmXfG2hk1ygnF4LyfcPVxM6tMzYjAmGdWGLWHa29ysr4uL

**Comment by steemplus** [comment]
Fixed
