### ISSUE TITLE
Tip button found below the user's logged on Steemit account username and is clickable

### ISSUE THREAD

**Issue by josephace135** [stoodkev/SteemPlus#119]
#### Expected behavior
When using busy.org, a user's logged on Steemit account should not have a ***Tip*** icon/button, since it would be redundant to send a tip on his own account.

#### Actual behavior
When reading your own post, ***Tip*** button appears below your username. Lastly, the ***Tip*** button is clickable and opens a SteemConnect window wherein the transaction shows that "Tip sent from username to username using steem-plus tipping system!"; for example ""Tip sent from josephace135 to josephace135 using steem-plus tipping system!".

#### How to reproduce
* Open Chromium browser.
* Go busy.org.
* Make ***SteemPlus***  switched for use in busy.org.
* Click any post of yours.
* The bug appears wherein the ***Tip*** button appears below the username.
* Click the ***Tip*** button and select an amount to tip; after that a new tab would be opened for SteemConnect.
* The user would found out that the transaction for tipping is between two the same usernames.

* Browser version: Chromium Version 58.0.2988.0
* App/Plugin version: SteemPlus 2.17.8
* Device: HP Notebook
* Operating system: Windows 10 64-bit

#### Recording Of The Bug
https://youtu.be/vALXaMGPHdY

**Comment by josephace135** [comment]
Update the bug still appears in Busy with the latest version of SteemPlus, 2.17.9.

**Comment by steemplus** [comment]
Will be fixed in version 2.18.1 (coming soon)

**Comment by josephace135** [comment]
That would be great @steemplus :)
