### ISSUE TITLE
Blog Histogram not displayed properly

### ISSUE THREAD

**Issue by josephace135** [stoodkev/SteemPlus#122]
#### Expected behavior
When activating the “Blog Histogram” which belongs to the “Steemit More Info Features”, the histogram that shows both the “posts” and “resteem” must be displayed in both the normal mode or in night mode.

#### Actual behavior
Upon activation of “Blog Histogram” only the total number of posts and resteemed posts is shown leaving the whole space intended for the histogram empty regardless if it is in normal more or in night mode.

#### How to reproduce
* Open Chromium browser.
* Click the “SteemPlus” plugin icon found next to the URL bar. 
* Click “Settings”.
* Look for “Steemit More Info Features” and enable “Blog Histogram”.
* Go to your “Blog”.
* The bug appears wherein the histogram is not shown, leaving the space provided empty and happens to both normal and night mode.

<br>

* Browser version: Chromium Version 58.0.2988.0
* App/Plugin version: SteemPlus 2.17.9
* Device: HP Notebook
* Operating system: Windows 10 64-bit

#### Recording Of The Bug
Bug appears in 1:20 until the end of the recording.
https://youtu.be/XphmiIIdQFA

**Comment by josephace135** [comment]
In the new version (2.18), the Blog Histogram is still not shown properly.
![blog histogram not shown version 2 18](https://user-images.githubusercontent.com/35374763/42573355-7c61a492-854e-11e8-89ab-599c1d25b473.PNG)

**Comment by steemplus** [comment]
Fixed

**Comment by josephace135** [comment]
That's great to hear @steemplus . Looking forward for the upcoming version :)
