### ISSUE TITLE
Comment gets published immediately even if the user hasn't picked a GIF

### ISSUE THREAD

**Issue by josephace135** [stoodkev/SteemPlus#123]
#### Expected behavior
When a user is going to *comment* on a certain post for which the content is composed of texts/words plus a GIF photo, it should be published manually by the user, once he is done picking his desired GIF.

#### Actual behavior
After the user inputs his message on his comment and taps the "GIF" button thereafter, upon placing keywords, the comment gets published immediately even if the searching for the GIF hasn't completed yet.

#### How to reproduce
* Open Chromium browser.
* Click the “SteemPlus” plugin icon found next to the URL bar. 
* Click “Settings”.
* Look for “Steemit More Info Features” and enable “Gif Picker”.
* Select a post that you'd want to comment.
* Enter a text that would serve as your comment.
* Tap the "GIF" button.
* Enter the keyword of the GIF that you'd want to be included in your comment.
* After a few seconds, the bug occurs, for which the comment gets published without clicking the "Post" button.

#### Recording Of The Bug
https://youtu.be/OvS4Qw3m19I

#### Environment
* Browser version: Chromium Version 58.0.2988.0
* App/Plugin version: SteemPlus 2.18
* Device: HP Notebook
* Operating system: Windows 10 64-bit

**Comment by stoodkev** [comment]
Fixed in coming version.
