### ISSUE TITLE
[2.18.1] Boost Button doesn't handle comment permalinks and opens empty container

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#126]
#### Expected behaviour

In the event that that the page I'm post on was triggered by a me clicking on a comment I should either be presented with one of the following when I try to "boost" it using SteemPlus. 

1. I should not be able to click on the boost button if the permalink is not valid for boosting. 
2. I should remove/ignore the comment details from the permalink in the event they're present.
3. Upon click of the boost button I should be given an indication that the boost button cannot be used to boost comments and asked if I would like to boost the main post. 
4. In the event the chosen boosting provider supports comment voting I should be able to boost the comment. 

#### Actual Behaviour

When I try to boost a post when the permalink contains comment details the pop up fails to load and simply shows an empty white container. 

#### Pre-requistes

1. The account which you're to test should have made at least one comment on the Steem blockchain. 

#### Steps to reproduce

1.  From a fresh install download SteemPlus  [here](https://busy.org/@tobias-g/[https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj)
2.  Complete the on-boarding flow and sign in via steemconnect
3.  You will be redirected to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4.  Go to busy.org and sign in with your account.
5.  Go to settings ensure you have “Boost Button” enabled within the settings shown in extensions pop up window, this should be enabled by default.
6.  Within busy, go to comments and click on any comment within the list. 
7. Once redirected to the comment, click on the 3 dot menu shown in the bottom bar. Note: If you have the floating post bar enabled you may need to scroll before it's visible, at the moment it appears below the posting bar. Please see video for further indication surroding the issue I mention here.
8. Once this menu is launched, click on boost. 
9. Note that the boost modal doesn't load and blank container is provided. 

 #### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: 2.18.1  (Updated:  July 18, 2018)

#### Recording of issue

The following video shows this issue in more detail:

https://www.youtube.com/embed/kSDYAARjBrc

#### Error  
  
The following errors are provided within the console upon the error occurring:

![image.png](https://ipfs.busy.org/ipfs/QmemCjKWCKae3d17zxjvS7XchfxYXrEiFJr2QzmQwLAr7w)

**Comment by stoodkev** [comment]
I dont like comment voting, I ll just hide the button
