### ISSUE TITLE
[2.18.1] Edit signature appears following the loading of post and takes you to @undefined/settings

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#128]
#### Expected behaviour

There are two possible expected behaviours which could take place:

1. The edit signature post is always present within "Write quick post" option and is always clickable, upon pressing the edit signature option. 
2. The edit signature option should not be provided to the user in the "write quick post" area.

#### Actual Behaviour

By default, the edit signature option is not provided to a user within the "Write quick post" option within SteemPlus, however when you click on a post and it loads as an overlay over the top of the page it will cause the edit signature option to appear within the write quick post section. Upon clicking the edit signature option it will take you to the following address:

https://busy.org/@undefined/settings

#### Steps to reproduce

1.  From a fresh install download SteemPlus  [here](https://busy.org/@tobias-g/[https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj)
2.  Complete the on-boarding flow and sign in via steemconnect    
3.  You will be redirected to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4.  Go to busy.org and sign in with your account.
5.  Go to settings ensure you have “Add Signature” enabled within the settings shown in extensions pop up window, this should be enabled by default.
6.  Go to any post on the news feed, ensure that it's loaded as an overlay of the page. 
7. Close the post and note that the edit signature option appears. 
8. Click on edit signature and note it takes you to https://busy.org/@undefined/settings

 #### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: 2.18.1  (Updated:  July 18, 2018)

#### Recording of issue

The following video shows this issue in more detail:

https://www.youtube.com/embed/9bClqAbLGHk

**Comment by stoodkev** [comment]
Will work directly on page load now
