### ISSUE TITLE
SteemPlus [2.18.1] Post menu options are not accessing in the floating bar when a post is loaded as an overlay on busy.org and poor user experience when a post is loaded in a full page view

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#130]
#### Expected behaviour

The post menu options located in the floating post bar should be accessible when a post is loaded as an overlay on busy.org. Upon press of the post menu options when a post is loaded in full page view, the menu options should load above the post bar.

#### Actual Behaviour

When clicking on the posting menu options in the floating post bar when a post is loaded as an overlay the post options will not been shown to a user. When you click on the post menu option in the floating post bar in full post view the menu options will appear below the floating bar, this giving an indication that nothing happened. 

#### Steps to reproduce

1.  From a fresh install download SteemPlus  [here](https://busy.org/@tobias-g/[https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj)
2.  Complete the on-boarding flow and sign in via steemconnect
3.  You will be redirected to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4.  Go to busy.org and sign in with your account.
5.  Go to settings ensure you have “Float Post's Voting Bar” enabled within the settings shown in extensions pop up window, this should be enabled by default.
6.  Go to the news feed and click on any post with a comment. The post should open in an overlay the new feed.
7. Click on the three-dot menu, located within the floating post bar. 
8. Note that nothing happens, now with the URL populated in your address bar refresh the page and you will be taken to the full page view of the post. 
9. Scroll down to halfway through the post and click the three-dot menu locating in the floating menu bar. Click this once. Note that it appears that nothing happens. 
8. Scroll down and note that menu appears. 

 #### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: 2.18.1  (Updated:  July 18, 2018)

#### Recording of issue

The following video shows this issue in more detail:
https://www.youtube.com/embed/KgQpUzt_xds

**Comment by stoodkev** [comment]
I ll look into it, it might take a while
