### ISSUE TITLE
SteemPlus [2.18.1] Following table doesn't load on Steemit

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#131]
This was previously reported but looks like it never made it to GitHub. The issue is still present on my device on the latest version. 

https://busy.org/@kodeblacc/filter-and-sorting-feature-for-following-list-is-missing

 #### Environment

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: 2.18.1  (Updated:  July 18, 2018)

**Comment by stoodkev** [comment]
This is working as intended. This feature is only working "online", you need to connect via SteemConnect to access it.

**Comment by tobias-g1** [comment]
Just to let you know even when I'm logged in it doesn't load the following table. I may not have provided enough info and assumed that the post was enough, my bad.
