### ISSUE TITLE
Incorrect Pending Rewards

### ISSUE THREAD

**Issue by josephace135** [stoodkev/SteemPlus#133]
#### Expected behavior
When accessing the “Rewards” tab both in busy and steemit, the author’s estimated pending payout  for each post should take into account the specific reward type such as “Power Up 100%” and “Decline Payout”.
#### Actual behavior
Upon accessing the “Rewards” tab both in busy and steemit, the author’s estimated pending payout for all posts are displayed and expressed by the “50% SBD and 50% SP” reward type regardless if the post’s reward type is either “100% Steem Power” or “Decline Payout”.

#### How to reproduce
In replicating this issue, the author must have a post that is any of the three reward types (Power Up 100%, 50% SBD and 50% SP and Decline Payout).
* Go to your account page and make sure that the SteemPlus plug-in switched for use either in busy or steemit.
* Click “SteemPlus”; for busy it is next to “Activity” whereas for steemit it is next to “Replies”.
* For “Author”, tap “Pending” button.
* The issue appears for which the estimated pending payout for all posts with either of the two reward type(“Power Up 100%” and “Decline Payout”) are expressed in “50% SBD and 50% SP” reward type.

#### Environment
* Browser version: Chromium Version 58.0.2988.0
* App/Plugin version: SteemPlus 2.18.1
* Device: HP Notebook
* Operating system: Windows 10 64-bit

#### Recording Of The Bug
Post that has a reward type of “Power Up 100%”.
- https://steemit.com/utopian-io/@josephace135/steemplus-2-18-maximum-available-sp-for-delegation-is-inaccurate-in-busy
![100 power up](https://user-images.githubusercontent.com/35374763/43045552-340ef576-8ded-11e8-8e04-42d938bd49b1.PNG)

Posts that has a reward type of “Decline Payout”
- https://steemit.com/steem/@steemitblog/blockchain-update-4-resource-credit-implementation-details
- https://steemit.com/steemit/@steemitblog/applications-team-update-hivemind-communities-sign-ups-developer-tools-condenser-and-more

![decline payout](https://user-images.githubusercontent.com/35374763/43045557-43089ae6-8ded-11e8-8137-0bbcdc2e0832.PNG)

**Comment by stoodkev** [comment]
Indeed, that is sth we should change later.
Thanks for notifying us

**Comment by josephace135** [comment]
You're welcome @stoodkev .
