### ISSUE TITLE
Mentions tab not working

### ISSUE THREAD

**Issue by josephace135** [stoodkev/SteemPlus#134]
#### Expected behavior
When accessing the “Mentions” tab, all posts/comments that the author is being mentioned should be displayed.

#### Actual behavior	
Upon accessing the “Mentions” tab in Steemit, the “Mentions” tab isn’t appearing and is being displayed with an infinite screen loading. At the same time, accessing “Mentions” tab in busy, a blank page appears.

#### How to reproduce
* Go to your account page and make sure that the SteemPlus plug-in is switched for use either in busy or Steemit.
* In Steemit or busy, tap the button for “SteemPlus”.
* In the dropdown menu for “SteemPlus”, click “Mentions”.
* After clicking, the bug appears wherein the “Mentions” tab takes an infinite loading (Steemit) and blank page (busy).

#### Environment
* Browser version: Chromium Version 58.0.2988.0
* App/Plugin version: SteemPlus 2.18.1
* Device: HP Notebook
* Operating system: Windows 10 64-bit

#### Issue
Looking at the console, it throws the following error for **mentions_tab.js** (both in busy and steemit):
Uncaught ReferenceError: HtmlReady is not defined
- at getImagePostSummary at line 422:
<code>var rtags = HtmlReady(htmlText, {mutate: false})</code>
- at createSummaryMention at line 260:
<code>var urlImgMentionDisplayed = getImagePostSummary(mentionItem);</code>
- at createRowsMentionTab at line 216:
<code>var el = createSummaryMention(mentionTabElement);</code> 
- at Object.success at line 161:
<code>createRowsMentionTab(mentionsTab, type, reset);</code>

#### Recording Of The Bug
In busy.org:

https://youtu.be/bnAGOKjw3lc

In Steemit:

https://youtu.be/4E6Aa2J0GIw

**Comment by tobias-g1** [comment]
Does it throw an error in the console? I thought I had this issue, but after a while it did load.

**Comment by josephace135** [comment]
Hi @tobias-g1 , yes it does indicate error in the console both in steemit and in busy.
