### ISSUE TITLE
Viewing Account Details With SteemPlus Shows That SP Value Is Same As Estimated Account Value Which is Incorrect (SP!=Account Value)

### ISSUE THREAD

**Issue by realrufans** [stoodkev/SteemPlus#137]
#### Expected behavior
When viewing an account wallet on steemit.com via SteemPlus, It's expected for the  ```SP``` value of the account to differ from the account estimated value.

#### Actual behavior
The SP value of an account is same as the **Account Value** 

#### How to reproduce
- Click on **Wallet** of an account, then the note **Steem Power** value
- scroll down to view the account details  via SteemPlus by clicking on the SteemPlus  icon<Center>
- Note the ```SP```

#### Environment
* Browser version: Version 68.0.3440.75 (Official Build) (64-bit)
* App/Plugin version: SteemPlus 2.18.2.1
* Device: System Model HP Laptop 15-bs0xx
* Operating system: Windows 10 64-bit

#### Recording Of The Bug
https://youtu.be/z5YFyOU49Zc

**Comment by tobias-g1** [comment]
I'm not sure what you mean here, you might want to explain in more detail as I think it's working as expected and can't see what's wrong based on your video.

**Comment by realrufans** [comment]
![sc](https://user-images.githubusercontent.com/33923021/43347445-3fef3ac8-91ed-11e8-9766-daf557da27c9.jpg)

From the image above,  the```Sp``` values are different.

**Comment by tobias-g1** [comment]
The top value in the Steem power section is in STEEM, the value for SP within the value pop up is in 
US Dollars ($).

**Comment by realrufans** [comment]
okay i got it
