### ISSUE TITLE
Invalid CSS at beneficiaries.css

### ISSUE THREAD

**Issue by abitrolly** [stoodkev/SteemPlus#148]
https://github.com/stoodkev/SteemPlus/blob/d9f268c175156bf8a87516af070a194bd5c4bca0/src/css/beneficiaries.css#L57-L59

I don't know how it is supposed to work, so not cleanup PR from my side.

**Comment by steemplus** [comment]
Hi abitrolly, can you explain a little bit more ?
Thank you,
Steem-plus

**Comment by abitrolly** [comment]
No problem. Just paste the CSS into https://jigsaw.w3.org/css-validator/#validate_by_input to see the error.

![image](https://user-images.githubusercontent.com/8781107/44507851-aec69300-a6de-11e8-939d-5581ee373114.png)

**Comment by steemplus** [comment]
oh okay! Thanks, that has been fixed.
