### ISSUE TITLE
Steem Level Badge

### ISSUE THREAD

**Issue by bflanagin** [stoodkev/SteemPlus#150]
Not sure if I'm not reading it correctly or if its a bug but I believe the badge isn't reporting my level correctly. 

![screenshot from 2018-08-23 10-06-34](https://user-images.githubusercontent.com/10382037/44534125-a78e8d80-a6bc-11e8-87a3-da378a0cdb1a.png)

**Comment by steemplus** [comment]
Hi bflanagin, your level is correct, what were you expecting?

**Comment by stoodkev** [comment]
Why not ? We ve divided each rank in three subdivisions.
The rank is calculated in VESTS (proportional to SP), Minnow III will then be around 500SP (it fluctuates due to the VEST to SP conversion)

**Comment by bflanagin** [comment]
I was just reading it wrong. I didn't notice that the tooltip changes and I was reading it as 'Plankton I' requires 65SP which I was well over, and  not that I had 65SP to go before reaching 'Plankton I.' 

Thanks for the clarification on how the ranks are calculated, and sorry for the false flag issue.
