### ISSUE TITLE
retrieve 1000 followers at a time to speed up the Followers Table feature

### ISSUE THREAD

**Issue by harpagon210** [stoodkev/SteemPlus#16]
#### Proposal
To speed us the process of fetching the followers for the users that have a lot of followers, increase the number of followers retrieved in one call to the steem API (the maximum of followers that the steem API can retrieve is actually 1000, [see steem API source code, line 79](https://github.com/steemit/steem/blob/1cfdf8101ec415156b155c9ec90b0a4d439a039f/libraries/plugins/apis/follow_api/include/steem/plugins/follow_api/follow_api.hpp#L74))

#### Mockups
[in the file "SteemPlus/src/js/followers_table.js"](https://github.com/stoodkev/SteemPlus/blob/6d0e41815eb0f62a1bb09e8e95931841fdb0769a/src/js/followers_table.js#L111)

replace
```
steem.api.getFollowers(username, lastFollower, 'blog', 100, function(err, response){
        // console.log(err);
        resolve(response);
});
```

by
```
steem.api.getFollowers(username, lastFollower, 'blog', 1000, function(err, response){
        // console.log(err);
        resolve(response);
 });
```
#### Benefits
This will substantially decrease the number of calls make to the steemjs API

**Comment by stoodkev** [comment]
Thanks, it was implemented.
