### ISSUE TITLE
[3.1.0.1] Tags clear after cancelling edit contribution to Utopian pop up via Steemit

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#169]
#### Expected behavior

When selecting the edit option after indicating that my post is for Utopian I should be able to cancel the edit pop up without it affecting my contribution or any of the contents that were previously entered. 

#### Actual Behaviour

If you select edit when creating a contribution to Utopian via SteemPlus and then cancel that edit, the tags will be cleared.

#### Steps to reproduce

From a fresh install download SteemPlus [here](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj)
2.  Complete the on-boarding flow and sign in via SteemConnect
3.  You will be redirected to Steemit.com (if you're already on the site, refresh to ensure the SteemPlus extension is working as expected).
4. Go to the create a new post page. 
5. Enter the Title as "Title"
6. Enter the Body as "Body"
7. Enter the first tag as utopian-io and press space. 
8. You will be presented with an option to contribute via Utopian. Select bug-hunting and the repository and `stoodkev/steemplus`, submit your selections. Note that the tags have now been populated with utopian-io bug-hunting. 
9. Click the edit option.
10. When the edit option appears, click the cancel option shown in the top right. 
11. Note that the tags are no longer present. 

#### Environment

- Browser: Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version of Testing: 3.1.0.1

#### Recording of issue

The following video shows this issue in more detail:

https://youtu.be/AU80agJ9OBY

**Comment by stoodkev** [comment]
This is the desired behavior.
