### ISSUE TITLE
If all texts on post editor is cleared on Steemit, side by side becomes nonexistent. Post editor reverts to default steemit view.  

### ISSUE THREAD

**Issue by HarryHeights** [stoodkev/SteemPlus#188]
#### Expected Behaviour
I expected that the side-by-side post editor view that steemplus makes possible would be consistent even though I emptied the content on the post editor. 

#### Actual Behviour
The post editor loses the side-by-side view when I clear the contents on it.

#### How to reproduce
This wouldn't be reproducible if you use the clear button on the editor.
To reproduce this error;

- Create or copy content into the post editor
- Don't clear the content. Automatically, it becomes a draft, meaning it will be available when you leave the post editor and surf through other menus. 
- After leaving the post editor, access it again. 
- Clear out the content by highlighting all with `ctrl+A` and clearing it with `backspace`
- After the editor is cleared, type in new texts.
- See that the side-by-side view is no longer functional. 

#### Video 

https://youtu.be/uFgFDSSFyT0

**Comment by stoodkev** [comment]
Not an issue, we actually move the markdown preview that is already on Steemit to put it besides the input area.
The original preview has the same behavior and only appears when there is text in the textarea.
