### ISSUE TITLE
Feed+ Page is Unresponsive After Clicking Apply Multiple Times

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#26]
#### EXPECTED BEHAVIOR
Feed+ Page continues to be responsive after the user clicks the Apply button many times.

#### ACTUAL BEHAVIOR
Feed+ Page becomes unresponsive after the user clicks the Apply button many times.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Click on 'Feed+' 
4. Click the 'Apply' button 10-20 times very quickly
5. Scroll through the feed list and attempt to click on things

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![ApplyClicksStall.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520909009/rtzoybh3ubixjy0el06a.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/feed-page-is-unresponsive-after-clicking-apply-multiple-times">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by cedricguillas** [comment]
Fixed in version 2.5.3. Ready for release

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
