### ISSUE TITLE
Duplicate Posts Appear in Feed+ After Cycling Sort By Selections

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#27]
#### EXPECTED BEHAVIOR
A post never appears more than once in Feed+ list.

#### ACTUAL BEHAVIOR
A post appears many times in the Feed+ list if the user cycles through all selections in the 'Sort by' dropdown.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Follow the @stoodkev account
4. Click on 'Feed+'
5. Select 'Old' in 'Sort by' dropdown
6. Select 'Payout' in 'Sort by' dropdown
7. Select 'Votes' in 'Sort by' dropdown
8. Select 'Recent' in 'Sort by' dropdown

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![RepeatedFeedPost.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520909573/ccjcrrbgdaynlvvnnx6h.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/duplicate-posts-appear-in-feed-after-cycling-sort-by-selections">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
