### ISSUE TITLE
Wrong Reputation Value Displayed on Blog Page

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#28]
#### EXPECTED BEHAVIOR
Correct reputation is displayed on Blog Page.

#### ACTUAL BEHAVIOR
Incorrect reputation is displayed on Blog Page.  It shows the correct value until the Steem+ features load, at which point it drops to 25.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Click Account's Icon in Upper Right
4. Select 'Blog'

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![WrongReputation.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520910471/befc9n2a0wa67mvtma8m.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/wrong-reputation-value-displayed-on-blog-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
