### ISSUE TITLE
Thumbnails from DLive Do Not Display in Feed+

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#29]
#### EXPECTED BEHAVIOR
DLive thumbnails display in the Feed+ list.

#### ACTUAL BEHAVIOR
DLive thumbnails do not display in the Feed+ list and the preview text shows some markdown symbols.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Ensure you have DLive generated posts in your Feed
4. Click on Feed+
5. Locate the DLive posts

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![DLIveThumbnails.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520911253/l3dlsedkeyues7jobikt.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/thumbnails-from-dlive-do-not-display-in-feed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Use the SMI Post creator functions for image scrapping and text preview (like in votes, mentions) perhaps, it seems to better deal with images that are inside the posts, as well as for the preview text.

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
