### ISSUE TITLE
User Can Be Added to Feed+ Resteem Blacklist Multiple Times

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#30]
#### EXPECTED BEHAVIOR
User can only be added to the Resteem Blacklist once.

#### ACTUAL BEHAVIOR
User can be added to the Resteem Blacklist multiple times.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Follow the @stoodkev account
4. Click on 'Feed+'
5. Expand Resteems Filter
6. Select Blacklist
7. Click 'Add to Resteem Blacklist' on top post multiple times

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![RepeatedBlackList.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520911526/ugwswwqj8xnsw20ii5nv.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/user-can-be-added-to-feed-resteem-blacklist-multiple-times">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by cedricguillas** [comment]
Fixed in version 2.5.3. Ready for release

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
