### ISSUE TITLE
Unable to Read Reputation Filter on Feed+ Page in Night Mode

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#31]
#### EXPECTED BEHAVIOR
User is able to read the value they entered in the Reputation Filter field on the Feed+ page while in Night Mode.

#### ACTUAL BEHAVIOR
User is unable to read the value they entered in the Reputation Filter field on the Feed+ page while in Night Mode.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Click User Icon in Upper Right
4. Click Toggle Night Mode to activate Dark Theme
5. Click on 'Feed+'
6. Activate the Reputation Filter
7. Type a value into the Reputation Filter field
8. Click outside of Reputation Filter field to deselect
9. Attempt to read the value you entered

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![DarkThemeReputation.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520911961/h7kyu7yyfz4ftsi8zjvo.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/unable-to-read-reputation-filter-on-feed-page-in-night-mode">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
