### ISSUE TITLE
Market Element Duplicates in Account Menu After Clicking Steem = USD

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#32]
#### EXPECTED BEHAVIOR
Market Element of Account Menu is only listed once.

#### ACTUAL BEHAVIOR
Market Element of Account Menu is occasionally listed twice when the user clicks on Steem = USD.  This does not happen every time, but is fairly frequent.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Click Account Icon in Upper Right
4. Click on the bottom selection when it shows Steem = USD values

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![MarketMenuDuplicate.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520912591/mefl2hkgsvv5p6cvgd1d.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/market-element-duplicates-in-account-menu-after-clicking-steem-usd">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
