### ISSUE TITLE
Feed+ Filter Items Do Not Expand on the First Click After Loading Page

### ISSUE THREAD

**Issue by thewizardstudio** [stoodkev/SteemPlus#33]
#### EXPECTED BEHAVIOR
User must click Feed+ Filter items once to expand.

#### ACTUAL BEHAVIOR
User must click Feed+ Filter items twice to expand if they just loaded the page.

#### HOW TO REPRODUCE
1. Login to SteemPlus 2.5.1 on Chrome 65.0.3325.146
2. Go to Steemit.com
3. Click on 'Feed+'
4. Click once on a Filter item in an attempt to expand it
5. Click the same Filter item again

#### TESTING ENVIRONMENT
- **OS**: Windows 10 <br>
- **Browser**: Chrome 65.0.3325.146 <br>
- **App Version**: 2.5.1 <br>

#### RECORDING OF THE BUG
![SingleClickFeed.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520912941/smrmlhgmjjnalzj0hnz7.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/feed-filter-items-do-not-expand-on-the-first-click-after-loading-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed in version 2.5.3. Ready for release
