### ISSUE TITLE
SteemPlus Mentions Section shows only 14 days old or older Mentions. 

### ISSUE THREAD

**Issue by louis88-steemit** [stoodkev/SteemPlus#34]
#### Expected behavior
If you click on the new mentions button in the Steemit Addon SteemPlus to see his last mentions on the blockchain, I expect that the last mentions will be shown directly. Unfortunately, this is not the case at the moment.

#### Actual behavior
Currently, when you click on the mentions button, the posts and mentions of at least 14 days old posts are displayed. 

Today I got a mention on the Steemit platform and this is not shown. 
![screenshot ginabot](https://i.imgur.com/Mj1DzHD.png)

<sub>Screenshot shows a successful mention from rivalzzz to me this evening. I'm using GINAbot to see those messages.

#### How to reproduce
Install the Steem Plus Addon - Go to your Blog Section and switch to the Mentions Section. Here you see only older mentions older than 14 days.
![enter image description here](https://media.giphy.com/media/BoItgHyyMQZUK6mXqY/giphy.gif)

* Browser: Google Chrome Version 64.0.3282.186 (Offizieller Build) (64-Bit) - All Browser 
* Operating system:  Mac OS X

#### Recording Of The Bug

![enter image description here](https://i.imgur.com/v3YM6D2.png)

<sub>This Screenshot shows 14 days old Mentions </sub>
    
Would be great when this will be fixed.

thanks
@louis88  <- this is another mention

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@louis88/steemplus-mentions-section-shows-only-14-days-old-or-older-mentions">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Hi! We use steemData as a 3rd party for the mentions, when you ve posted that it was out of sync but it's running well now.
