### ISSUE TITLE
Not working deactivation of "Blog Histogram"

### ISSUE THREAD

**Issue by RivalzZz88** [stoodkev/SteemPlus#39]
#### Expected behavior
I installed the Steem-Plus addon and found the new features in the options. I activated the "Blog Histogram" in the settings and deactivated it again after I didn't like it ( See Gif )
The expectation was that the blog histogram is disabled again.

#### Actual behavior
When activating and deactivating the function in the AddOn option, the "BlogHistogram" is no longer deactivated but remains activated although the function was deactivated in the AddOn

#### How to reproduce

1. Install the Steem-Plus Addon in Google-Chrome > found on  https://steemit.com/@steem-plus
2. Go to the Settings after you logged in with steemconnect2
3. Scroll down to the "Blog Histogram" Function and activate it
4. Refresh the Page of a SteemitUser-Blogsite and there you see the Blog Histogram
5. Go back to settings and deactivate the Function "Blog Histogram"
6. You will countinously see the Blog Histogram on the Steemit-Blogpages of Users!

* Browser:  Google-Chrome Version 65.0.3325.162 (Offizieller Build) (64-Bit)
* Operating system: Win10 64bit

#### Recording Of The Bug
https://media.giphy.com/media/OTnMEPb7xGHy82UAU4/giphy.gif
https://gyazo.com/5ed4de368a5fd9d18b2b24b47fe3ef32
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@rivalzzz/not-working-deactivation-of-blog-histogram">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Thanks for noticing!
