### ISSUE TITLE
1up button is not visible even with steemplus extension active

### ISSUE THREAD

**Issue by kodeblacc** [stoodkev/SteemPlus#40]
#### Expected behavior
I expected that with the steemplus extension active, I should see the 1up icon to give 1up votes on utopian platform

#### Actual behavior
When the extension is active I don't see the 1up vote button until I click several times where the icon normally should be.

#### How to reproduce
- install the steemplus extension on google chrome
- login to utopian.io
- 1up button is unavailable until several clicks on the position it normally should be.
* Browser:  google chrome
* Operating system: window 7 pro

#### Recording Of The Bug
https://youtu.be/7TJVbYXwY2k
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/1up-button-is-not-visible-even-with-steemplus-extension-active">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Fixed in 2.5.3.4.
However, because of the new Utopian Bot behavior, posts will be now votable before moderation directly on 1up frontend.
Thanks for your contribution.
