### ISSUE TITLE
Add GIF button disappears following beneficiaries being added

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#42]
#### Expected behavior
When using SteemPlus I should have the ability to click on the GIF button at all stages of creating my post regardless of whether or not I have interacted with other elements of the create post page. 

#### Actual behavior
If I click on the add beneficiaries button I no longer have the ability to add a GIF to my post. 

#### How to reproduce
1. From a fresh install download SteemPlus [here](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj?hl=en)
2. Complete the onboarding flow and sign in via steemconnect
3. Go to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4. Ensure that you have all settings enabled within the SteemPlus extension, most importantly you will need beneficiaries, and Gif Picker (these should all be enabled by default). 
5. Click on create a new post icon (pen icon) located at the top right of the page on Steemit.com
6. Take note that a GIF button and an add beneficiaries button should be viewable on the page.
7. Click on the "add beneficiaries" button
8. Note that the GIF button is longer visible or usable to the user. 

Note: It will come back when you remove beneficiaries.

* Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
* Operating system: MacOS HighSierra Version 10.13
* Application Version: Version: 2.5.3.0 (Last Updated: Updated: March 18, 2018)

#### Recording Of The Bug

The following image can be used to view the issue described in this bug report:

![Mar-18-2018 15-27-04.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521387073/ayj17ygpym1jdyalckkr.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/add-gif-button-disappears-following-beneficiaries-being-added">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
@cedricguillas please check this.

**Comment by stoodkev** [comment]
It has been fixed. Thank you,
