### ISSUE TITLE
Profile Image should be clickable on vote history page

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#44]
#### Expected behavior
Clicking on a users profile image on the vote history page should take you the user's profile page, the behavior should be similar to behavior when you click on the user's account name on the vote history page. 

Note: The profile image is wrapped in ``` <a> ``` tag, therefore indicating on click it should take you the user profile. 

#### Actual behavior
Clicking on the user's profile image does nothing and doesn't take your the user's profile page.

#### How to reproduce
1. From a fresh install download SteemPlus [here](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj?hl=en)
2. Complete the onboarding flow and sign in via steemconnect
3. Go to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4. Ensure that you have all settings enabled within the SteemPlus extension, most importantly you will need Vote Tab enabled (this should all be enabled by default). 
5. Using the menu that appears when you click on your profile image on the main steemit page select wallet.
6. When in your wallet you will see a tab called "votes", click this option.
7.By default incoming votes will be selected, on this tab, you will see latest votes you have received, you will be shown a username, an image, and a link for the user who has voted on. Click on the profile image (you will see a hover effect (pointer) indicating that it is clickable). 
8. Nothing will happen upon click.

* Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
* Operating system: MacOS HighSierra Version 10.13
* Application Version: Version: 2.5.3.0 (Last Updated: Updated: March 18, 2018)

#### Recording Of The Bug
The following image shows that the profile image is wrapped in a ``` <a> ``` tag and therefore on click should take you the user's profile page:

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521388022/d9xafwsezneihwjixqyx.png)

The following image shows the behavior when the image is clicked as well as the steps to replicate:

![Mar-18-2018 15-57-23.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521389058/wfn06wfv0tqolyhk5fjc.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/profile-image-should-be-clickable-on-vote-history-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Link (not the image) will be clickable as of 2.6. Thanks
