### ISSUE TITLE
Unable to configure tag list within Feed Plus

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#45]
#### Expected behavior
When using FeedPlus you should have the option to only show posts on your feed filtered by a tag list which you can set within the filter options. When you select show tags only it should show a text area which allows you to configure the tags you wish to see. 

#### Actual behavior
When you select show tags only from the filter options you're not presented with a text area to configure the tags you wish to show. 

Note: You can see from my image that the text area is still set to ``` display: none``` following the click of show tags only, it should be showing the text area underneath the radio button.

#### How to reproduce
1. From a fresh install download SteemPlus [here](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj?hl=en)
2. Complete the onboarding flow and sign in via steemconnect
3. Go to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4. Ensure that you have all settings enabled within the SteemPlus extension, most importantly you will need FeedPlus enabled (this should all be enabled by default). 
5. Click on Feedplus which is located in the top navigation items on Steemit
6. Once FeedPlus is loaded you will see options located on right-hand side of the page which allows you to filter the feed. 
7. Click on the option tags to expand the tags options.
8. Upon click you will be presented with the following options: Show All Tags, Show Only (Show all tags will be selected by default), Click on Show Only
9. The show only option will be selected but the option to enter tags will not be present. 

* Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
* Operating system: MacOS HighSierra Version 10.13
* Application Version: Version: 2.5.3.0 (Last Updated: Updated: March 18, 2018)

#### Recording Of The Bug

The following image helps show the steps to reproduce for the issue mentioned within this contribution:

![Mar-18-2018 23-36-28.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521416695/ump9pxb0f0pc3smbtvn2.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/unable-to-configure-tag-list-within-feed-plus">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Fixed in 2.5.3.4
Thanks for the report
