### ISSUE TITLE
scrollbar border present for comments that are not lengthy and scroll bar unable to scroll to the bottom of the post without the default scrollbar

### ISSUE THREAD

**Issue by kodeblacc** [stoodkev/SteemPlus#47]
#### Expected behavior
A new scroll bar was seen when viewing my article on steemit today due to the steemplus extension, and it seems cool but I expected that posts that are not lengthy shouldn't require scroll bar and that the scroll bar should be able to defile the browser's original scroll bar by allowing me scroll to the bottom of the post without having to use the browser's scroll bar.

#### Actual behavior
- Comments that are not lengthy and shouldn't need a scrollbar, contains the scroll bar border

- When viewing my post the scroll bar is present but when using it to scroll it doesn't get to the last part of the post.

#### How to reproduce
- install steemplus extension and enable it
- login to steemit.com on PC
- open a post
- use the scrollbar and it won't get to the bottom of the post
- also the comments section with 1 line of comment shows the scrollbar border
<Hr>

* Browser:  google chrome
* Operating system: window 7 professional 

#### Recording Of The Bug
https://youtu.be/n5KGG7mW7lM

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/scrollbar-border-present-for-1-line-comments-and-scroll-bar-unable-to-scroll-to-the-bottom-of-the-post-without-the-default">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Fixed in 2.5.3.4
