### ISSUE TITLE
Request To run Promotion For Steemplus.

### ISSUE THREAD

**Issue by gutzygwin** [stoodkev/SteemPlus#49]
I would like for to request for your permission in promoting steemplus. 
Over the weeks, steemplus has bettered my steemit and busy experience. I've never felt more in control of my voting power and voting weight with the use of steemPlus.  
      I own a facebook page which i could use with the aid of an additional ad which i will provide to broadcast about steemplus. 
     I humbly request your permission and in doing so, I hope to contribute my best to SteemPlus. 

Thank you.

**Comment by stoodkev** [comment]
Hey man! Sure, please do! You can contact me on Discord to discuss this, thank you!
