### ISSUE TITLE
[SteemPlus] - Favorite table repeats itself

### ISSUE THREAD

**Issue by tolgahanuzun** [stoodkev/SteemPlus#54]
## Expected behavior

- I toured the Steemit page.
- I expect my favorite user table to work normally.
- Unique and 1 table.

## Actual behavior

- Steemit I'm on the pages.
- A new table is being produced on every page.
- It's a bug that repeats itself.

## How to reproduce

- I accept that I have chosen a favorite membership with the Steemplus plugin.
- I'm coming home.
- I'm going to the trend page.
- I'm going to the Hot or Promoted page.
- The favorite table on the right side repeats itself.

Browser: Chrome Version 65.0.3325.162 (Official Build) (64-bit)

Operating system: macOS Sierra

## Recording Of The Bug
![Kapture 2018-03-29 at 9.43.42.gif](https://steemitimages.com/DQmbtC9BNi69jL5Uhvy7ZkTaXsTtb3K1p5trXZ9uiSJt5K3/Kapture%202018-03-29%20at%209.43.42.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tolgahanuzun/steemplus-favorite-table-repeats-itself">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
We fixed it. Thank you.
