### ISSUE TITLE
Steem-Plus : Quick Switch shortcut to Busy not working

### ISSUE THREAD

**Issue by orlandumike** [stoodkev/SteemPlus#58]
For Steem-Plus [Chrome Store](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj?hl=en)
#### Expected behavior
When using the shortcut SHIFT + ALT + B, site switch to Busy

#### Actual behavior
Nothing happen

#### How to reproduce
Be on Steemit, Utopian or SteemD with SteemPlus activated.
Use the shortcut SHIFT + ALT + B => nothing happen.

It works fine for Utopian and SteemD and Steemit from the other platform

* Browser: Chrome
* Operating system: Windows 10
* Version: 2.7.0.1
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@orlandumike/quick-switch-shortcut-to-busy-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
It might be because the shortcut is already taken on Chrome, this is not a SteemPlus issue.
You can reset the shortcuts on the extension page.
