### ISSUE TITLE
Sincerity button doesn't appear following FeedPlus filtering

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#59]
#### Expected behaviour
The sincerity buttons should load every time on the FeedPlus page regardless of if I have applied a filter to the feed.

#### Actual behavior
The sincerity buttons load first time, however, they hide following a filter being applied to the feed.

#### How to reproduce
1. From a fresh install download SteemPlus [here](https://chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj/related?hl=en)
2. Complete the onboarding flow and sign in via steemconnect
3. Go to Steemit.com (if you're already on the site, refresh to ensure the steemplus extension is working as expected)
4. Ensure that you have all settings enabled within the SteemPlus extension, most importantly you will need FeedPlus enabled (this should all be enabled by default).
5. Click on Feedplus which is located in the top navigation items on Steemit
6. Once FeedPlus has loaded you will that a sincerity button will appear next to the post, this will display as one of the four following options: Human, Tell Us, Spammer or Bot
7. Change the number of posts shown on the feed, this can be done using Posts filter within the side options (right side), within the video I use 200.
8. Let the feed reload and wait for the sincerity button to appear. 
9. Note that it doesn't appear following the first load/filtering. 

Note: I have tested this with other filters and don't believe it's specific to post count, I believe it's related to actual filtering function rather than individual filters. 

#### Environment 

- Browser: Google Chrome (Version 65.0.3325.162 (Official Build) (64-bit))
- Device: MacBook Pro (Retina, 15-inch, Late 2013)
- Operating system: MacOS HighSierra Version 10.13
- Application Version: Version: 2.8.1.1 (Last Updated: April 4, 2018)

#### Recording Of The Bug
An image which shows the bug in more detail can be found below:

![Bug-Image-SteemPlus](http://pichoster.net/images/2018/04/06/1adad6d7d6b418185a73b7c65763f618.gif)
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/sincerity-button-doesn-t-appear-following-feedplus-filtering">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by steemplus** [comment]
Fixed
