### ISSUE TITLE
Hardcoded Stoodkev profile link in post count in user profile

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#71]
#### Expected

When I click on the post number in my profile it will take me to my posts. 

#### Actual 

If I click on posts which are now shortened based on the recent update it will take me to https://steemit.com/@stoodkev rather than my feed of posts.

![image](https://user-images.githubusercontent.com/17148879/39101716-f5578c02-4694-11e8-8801-9c7e7a39f55d.png)

Apologies for the short explanation and hope it's enough, will elabarote in the morning (UK) if more info is needed, but hopefully should be enough for you to push a fix.

**Comment by steemplus** [comment]
Fixed. Thank you!
