### ISSUE TITLE
Steemplus: Wallet filter doesn't show details of recent sent transactions.

### ISSUE THREAD

**Issue by kodeblacc** [stoodkev/SteemPlus#87]
#### Expected behavior
The wallet filter the extension provides should also show transactions of sent steem or steem backed dollars(SBD). Especially if the sent filter is turned on or active.
#### Actual behavior
On my wallet, when I make a transaction(send steem or sbd) the transaction doesn't show  except the extension is disabled.
#### How to reproduce
- install and activate the steemplus extension 
- login in to steemit website
- go to your wallet (please ensure the steemplus extension is active so the wallet filter is available and ensure the sent filter is active)
- perform a transaction (transfer steem or SBD)
- the transaction conducted is not shown until the extension is inactive. <hr>

PS: Don't rely on older sent transactions as it seems this issue is really recent and it'll be easier if the only the sent filter is active.

* Browser/App version: Google Chrome v 66.0.3359.139|| Steemplus  v 2.13.0.1 
* Operating system: Windows 7 Ultimate

#### Recording Of The Bug
https://youtu.be/XEA_crM3Dbo

**Comment by steemplus** [comment]
We get the data from SteemSQL which has a little delay. It can happen that the delay is too important so we give user the opportunity to use Steemit wallet (if delay > 3 minutes)
