### ISSUE TITLE
Able to make delegation button disappear on busy.org wallet

### ISSUE THREAD

**Issue by tobias-g1** [stoodkev/SteemPlus#9]
#### Expected behavior
The delegation option should always should shown within your wallet if it is enabled by a user using SteemPlus.

#### Actual behavior
If you quickly switch between activity and wallet you can make the delegation button disappear shown on your wallet profile. 

#### How to reproduce
1. Download steemplus from here: chrome.google.com/webstore/detail/steemplus/mjbkjgcplmaneajhcbegoffkedeankaj
2. Navigate to busy.org
3. Open steemplus by clicking the icon located in your extensions toolbar.
4. When pressed sign in using SteemConnect will appear, sign in.
5. Exit the pop up
6. Click on your profile and go to your wallet
7. A delegate button should appear underneath the current SBD and STEEM Prices
8. Click on activity and then quickly click on wallet again, the delegation button will appear. 
9. Repeat step 8, and the delegation button won't appear. 

Note: This seems to happen after two times for me.  

Browser: Google Chrome (Version 63.0.3239.132 (Official Build) (64-bit))
Operating system: MacOS HighSierra Version 10.13
Application Version: 2.3.2.1
Updated: January 28, 2018

#### Recording Of The Bug
A recording of the bug can be found here: https://d.tube/#!/v/tobias-g/2mbdjbnw

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/able-to-make-delegation-button-disappear-on-busy-org-wallet">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by stoodkev** [comment]
Can't reproduce the bug
